# @package _global_

defaults:
  - override /data: r1lite/lerobot_eef
  - override /model: unet_aug_idpenc

data:
  train:
    dataset_dirs: 
      - /home/ubuntu/projects/galabot/GalaxeaDP/data/R1LiteBottleAdjust

