# @package _global_

defaults:
  - override /data: r1pro/lerobot_joints
  - override /model: unet_aug_idpenc

data:
  train:
    dataset_dirs: 
      - /root/.cache/huggingface/lerobot/galaxea/R1ProBlocksStackEasy_joints/
