# @package _global_

defaults:
  - override /data: r1pro/lerobot_eef
  - override /model: unet_aug_idpenc

data:
  train:
    dataset_dirs: 
      - /home/ubuntu/.cache/huggingface/lerobot/galaxea/R1ProBlocksStackEasy_eef/
